version: "3"
services:
  appview:
    image: pinksea/appview
    environment:
      - PostgresConfig__Hostname=postgresql
      - PostgresConfig__Username=${POSTGRES_USERNAME}
      - PostgresConfig__Password=${POSTGRES_PASSWORD}
      - AppViewConfig__AppViewUrl=${APPVIEW_URL}
      - FrontendConfig__FrontendUrl=${FRONTEND_URL}
      - AppViewConfig__BackfillRelay=${BACKFILL_RELAY}
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - pinksea
    ports:
      - "5678:8080"
  frontend:
    image: pinksea/gateway
    build:
      context: .
      dockerfile: Dockerfile.Gateway
    environment:
      - GatewaySettings__AppViewEndpoint=${APPVIEW_URL}
      - GatewaySettings__FrontEndEndpoint=${FRONTEND_URL}
    networks:
      - pinksea
    ports:
      - "6789:8080"
  postgresql:
    image: postgres
    restart: always
    networks:
      - pinksea
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=PinkSea
    volumes:
      - pinksea_db:/var/lib/postgresql/data

networks:
  pinksea:

volumes:
  pinksea_db:
    driver: "local"
