version: "3"
services:
  appview:
    image: pinksea/appview
    environment:
      PostgresConfig__Hostname: postgresql
      PostgresConfig__Username: pinksea
      PostgresConfig__Password: pinksea 
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - pinksea
    ports:
      - "5678:8080"
  frontend:
    image: pinksea/gateway
    build:
      context: .
      dockerfile: Dockerfile.Gateway
    networks:
      - pinksea
    ports:
      - "6789:8080"
  postgresql:
    image: postgres
    restart: always
    networks:
      - pinksea
    environment:
      POSTGRES_USER: pinksea
      POSTGRES_PASSWORD: pinksea
    volumes:
      - pinksea_db:/var/lib/postgresql/data

networks:
  pinksea:

volumes:
  pinksea_db:
    driver: "local"
