// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PinkSea.Database;

#nullable disable

namespace PinkSea.Migrations
{
    [DbContext(typeof(PinkSeaDbContext))]
    [Migration("20250418110405_Add handle to user model")]
    partial class Addhandletousermodel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PinkSea.Database.Models.ConfigurationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientPrivateKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientPublicKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Configuration");
                });

            modelBuilder.Entity("PinkSea.Database.Models.OAuthStateModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OAuthStates");
                });

            modelBuilder.Entity("PinkSea.Database.Models.OekakiModel", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("AltText")
                        .HasColumnType("text");

                    b.Property<string>("AuthorDid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BlobCid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BlueskyCrosspostRecordTid")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("IndexedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsNsfw")
                        .HasColumnType("boolean");

                    b.Property<string>("OekakiTid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParentId")
                        .HasColumnType("text");

                    b.Property<string>("RecordCid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Tombstone")
                        .HasColumnType("boolean");

                    b.HasKey("Key");

                    b.HasIndex("ParentId");

                    b.HasIndex("Tombstone");

                    b.HasIndex("AuthorDid", "OekakiTid");

                    b.ToTable("Oekaki");
                });

            modelBuilder.Entity("PinkSea.Database.Models.TagModel", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("PinkSea.Database.Models.TagOekakiRelationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("OekakiId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TagId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OekakiId");

                    b.HasIndex("TagId");

                    b.ToTable("TagOekakiRelations");
                });

            modelBuilder.Entity("PinkSea.Database.Models.UserModel", b =>
                {
                    b.Property<string>("Did")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Handle")
                        .HasColumnType("text");

                    b.HasKey("Did");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PinkSea.Database.Models.OekakiModel", b =>
                {
                    b.HasOne("PinkSea.Database.Models.UserModel", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorDid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PinkSea.Database.Models.OekakiModel", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Author");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("PinkSea.Database.Models.TagOekakiRelationModel", b =>
                {
                    b.HasOne("PinkSea.Database.Models.OekakiModel", "Oekaki")
                        .WithMany("TagOekakiRelations")
                        .HasForeignKey("OekakiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PinkSea.Database.Models.TagModel", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oekaki");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("PinkSea.Database.Models.OekakiModel", b =>
                {
                    b.Navigation("TagOekakiRelations");
                });
#pragma warning restore 612, 618
        }
    }
}
